### PR TITLE
Algebra proposal faithful to Elliot's paper

### PR DESCRIPTION
**Pull request by FrancoAra**
The Event monad and monoid are still to be implemented, which are fairly simple, but the general idea shows off. This Algebra can, later on, be interpreted into composition of IOs.

[Elliot's paper](http://conal.net/papers/push-pull-frp/push-pull-frp.pdf)

### CODE REVIEW

**Comment by kolov** [comment]
Did you notice the build is failing?

**Comment by FrancoAra** [comment]
yhea, I think it is scalafmt, I will improve for Monday's presentation

**Comment by kolov** [comment]
Oh yeah, I had to run scalafmt too to my PR

**Comment by kolov** [comment]
Can you show an example coding a simple signal network, like this one: https://wiki.haskell.org/FRP_explanation_using_reactive-banana
 (example coding https://github.com/kolov/scalaz-reactive/blob/69095de92ce9e84ddd8bdc6d2019f458e2275c65/src/main/scala/examples/Synthesizer.scala#L35)

**Pull request merged**
